export interface Ingredient {
	name: string;
	type: string;
	appearance: string;
	flavorProfile: string;
	otherQualities?: string[];
}

export const INGREDIENTS = [
	{
		name: "Ground beef patties",
		type: "Meat",
		appearance:
			"Round, thick, usually about a quarter to half inch thick, raw meat is pink and turns brown when cooked",
		flavorProfile: "Rich, meaty, slightly fatty, savory",
	},
	{
		name: "Ground turkey patty",
		type: "Meat",
		appearance: "Round, thick, similar to ground beef but lighter in color",
		flavorProfile: "Mild, slightly gamey, less fatty than beef",
		otherQualities: ["low calorie", "healthy"],
	},
	{
		name: "Portobello mushroom cap",
		type: "Meat substitute",
		appearance: "Large, flat, dark brown cap",
		flavorProfile: "Earthy, meaty texture, juicy",
		otherQualities: ["low calorie", "healthy", "vegetarian", "vegan"],
	},
	{
		name: "Tofu patty",
		type: "Meat substitute",
		appearance: "Round, white, firm",
		flavorProfile: "Mild, slightly sweet, absorbs other flavors well",
		otherQualities: ["low calorie", "healthy", "vegetarian", "vegan"],
	},
	{
		name: "Ground lamb patties",
		type: "Meat",
		appearance: "Round, raw meat is a deep red, cooks to a lighter brown",
		flavorProfile: "Rich, slightly gamey, fatty",
	},
	{
		name: "Thinly sliced steak",
		type: "Meat",
		appearance: "Thin strips, varying shades of red and pink",
		flavorProfile:
			"Beefy, savory, can be tender or slightly chewy depending on the cut",
	},
	{
		name: "Ground pork patties",
		type: "Meat",
		appearance: "Round, raw meat is pale pink, cooks to a white or light brown",
		flavorProfile: "Mild, slightly sweet, fatty",
	},
	{
		name: "Ground chicken patties",
		type: "Meat",
		appearance: "Round, pale color similar to turkey",
		flavorProfile: "Mild, slightly denser than turkey, less fatty",
		otherQualities: ["low calorie", "healthy"],
	},
	{
		name: "Quinoa and black bean patty",
		type: "Meat substitute",
		appearance:
			"Round, dark speckled with black beans and lighter quinoa grains",
		flavorProfile: "Earthy, with a soft texture and a nutty bean flavor",
		otherQualities: ["low calorie", "healthy", "vegetarian", "vegan"],
	},
	{
		name: "Blue cheese",
		type: "Cheese",
		appearance: "Crumbly, with distinctive blue or green veins",
		flavorProfile: "Sharp, salty, tangy with a strong pungent aroma",
	},
	{
		name: "Smoked gouda",
		type: "Cheese",
		appearance: "Pale yellow with a smoky brown rind",
		flavorProfile: "Rich, creamy, smoky",
	},
	{
		name: "Swiss cheese",
		type: "Cheese",
		appearance: "Pale yellow, characterized by large holes",
		flavorProfile: "Mild, nutty, slightly sweet",
	},
	{
		name: "Goat cheese",
		type: "Cheese",
		appearance: "Soft, creamy white",
		flavorProfile: "Tangy, earthy, creamy",
	},
	{
		name: "Feta cheese",
		type: "Cheese",
		appearance: "Crumbly, white",
		flavorProfile: "Briny, tangy, slightly grainy",
	},
	{
		name: "Provolone cheese",
		type: "Cheese",
		appearance: "Smooth, pale yellow",
		flavorProfile: "Mild, slightly sweet and buttery",
	},
	{
		name: "Mozzarella cheese",
		type: "Cheese",
		appearance: "Soft, white, and moist",
		flavorProfile: "Mild, milky, with a slight tang",
	},
	{
		name: "Brie cheese",
		type: "Cheese",
		appearance: "Soft with a white mold rind",
		flavorProfile: "Rich, buttery, mild with earthy undertones",
	},
	{
		name: "Manchego cheese",
		type: "Cheese",
		appearance: "Firm, pale yellow",
		flavorProfile: "Nutty, slightly tangy, well-aged versions are sharper",
	},
	{
		name: "Gruyere cheese",
		type: "Cheese",
		appearance: "Pale yellow, slightly grainy",
		flavorProfile: "Rich, creamy, nutty",
	},
	{
		name: "Cream cheese",
		type: "Cheese",
		appearance: "Soft, smooth, white",
		flavorProfile: "Mild, creamy, slightly tangy",
	},
	{
		name: "Chive cream cheese",
		type: "Cheese",
		appearance: "Soft, white with specks of green chives",
		flavorProfile:
			"Creamy, mild cheese flavor enhanced with fresh, oniony chives",
	},
	{
		name: "Whole wheat bun",
		type: "Bread",
		appearance: "Darker brown, grainy texture with visible whole grains",
		flavorProfile: "Nutty, hearty",
	},
	{
		name: "Focaccia bun",
		type: "Bread",
		appearance:
			"Thick, soft, dimpled surface often topped with herbs and olive oil",
		flavorProfile: "Olive oil-rich, aromatic, slightly salty",
	},
	{
		name: "Brioche bun",
		type: "Bread",
		appearance: "Golden brown, shiny glaze, soft and fluffy",
		flavorProfile: "Rich, buttery, slightly sweet",
	},
	{
		name: "Ciabatta bun",
		type: "Bread",
		appearance: "Rustic, rectangular, porous texture",
		flavorProfile: "Chewy, crusty exterior, mild flavor",
	},
	{
		name: "Pretzel bun",
		type: "Bread",
		appearance: "Dark brown, shiny, coarse salt on top, dense",
		flavorProfile: "Slightly sweet, malty, distinctive lye-treated crust",
	},
	{
		name: "Multi-grain bun",
		type: "Bread",
		appearance:
			"Hearty, topped with various seeds like sesame, sunflower, and pumpkin",
		flavorProfile: "Rich grain flavor, nutty, crunchy from the seeds",
	},
	{
		name: "Hoagie roll",
		type: "Bread",
		appearance: "Long, soft, white, slightly crusty",
		flavorProfile: "Mild, soft interior, slightly chewy",
	},
	{
		name: "Garlic bun",
		type: "Bread",
		appearance: "Soft, often buttery and topped with minced garlic and herbs",
		flavorProfile: "Rich garlic flavor, buttery, aromatic",
	},
	{
		name: "Kaiser bun",
		type: "Bread",
		appearance: "Round, crusty, often topped with poppy seeds",
		flavorProfile: "Slightly crusty exterior, soft inside, mild flavor",
	},
	{
		name: "Walnut-crusted bun",
		type: "Bread",
		appearance: "Soft bun topped with crunchy walnut pieces",
		flavorProfile: "Nutty, rich, adds texture to the soft bun",
	},
	{
		name: "Sesame seed bun",
		type: "Bread",
		appearance: "Light brown, topped with sesame seeds",
		flavorProfile: "Soft with a nutty taste from the sesame seeds",
	},
	{
		name: "Potato bun",
		type: "Bread",
		appearance: "Soft, light golden color, fluffy texture",
		flavorProfile: "Mild, slightly sweet, very soft",
	},
	{
		name: "Naan bun",
		type: "Bread",
		appearance: "Flat, soft, with a slightly bubbly texture",
		flavorProfile: "Mild, doughy, with a slight tang",
	},
	{
		name: "Poppy seed bun",
		type: "Bread",
		appearance: "Soft bun sprinkled with poppy seeds",
		flavorProfile: "Slightly sweet bun with crunchy, nutty poppy seeds",
	},
	{
		name: "Caramelized onions",
		type: "Vegetable",
		appearance: "Deep golden brown, soft, sticky",
		flavorProfile: "Sweet, rich, with a deep umami flavor",
	},
	{
		name: "Roasted bell peppers",
		type: "Vegetable",
		appearance: "Soft, charred skin, vibrant red, green, or yellow",
		flavorProfile: "Sweet, smoky",
	},
	{
		name: "Arugula",
		type: "Vegetable",
		appearance: "Small green leaves, slightly ragged edges",
		flavorProfile: "Peppery, slightly bitter",
	},
	{
		name: "Sliced radishes",
		type: "Vegetable",
		appearance: "Thin, crisp, vibrant red and white",
		flavorProfile: "Crunchy, peppery",
	},
	{
		name: "Watercress",
		type: "Vegetable",
		appearance: "Small, dark green leaves on thin stems",
		flavorProfile: "Peppery, slightly tangy",
	},
	{
		name: "Roasted beet slices",
		type: "Vegetable",
		appearance: "Deep red or golden, soft texture",
		flavorProfile: "Sweet, earthy",
	},
	{
		name: "Red onion",
		type: "Vegetable",
		appearance: "Crisp, vibrant purple layers",
		flavorProfile: "Sharp, slightly sweet when cooked",
	},
	{
		name: "Sauteed onions and peppers",
		type: "Vegetable",
		appearance: "Soft, golden onions with soft, multicolored peppers",
		flavorProfile: "Sweet, savory",
	},
	{
		name: "Pickled vegetables",
		type: "Vegetable",
		appearance: "Crisp, vibrant colors, usually in a brine",
		flavorProfile: "Tangy, salty, slightly sweet",
	},
	{
		name: "Cilantro",
		type: "Herb",
		appearance: "Bright green, delicate leaves",
		flavorProfile:
			"Fresh, citrusy, with a distinct flavor that some find soapy",
	},
	{
		name: "Grilled pineapple",
		type: "Fruit",
		appearance: "Golden brown char marks, juicy yellow flesh",
		flavorProfile: "Sweet, tangy, caramelized when grilled",
	},
	{
		name: "Caramelized pears",
		type: "Fruit",
		appearance: "Golden brown, soft",
		flavorProfile: "Sweet, slightly floral, rich",
	},
	{
		name: "Tomato",
		type: "Vegetable",
		appearance: "Bright red, juicy",
		flavorProfile: "Sweet, slightly acidic",
	},
	{
		name: "Mixed wild mushrooms",
		type: "Vegetable",
		appearance: "Variety of shapes and colors, from light to dark",
		flavorProfile:
			"Earthy, umami, varies from mild to intense depending on the type",
	},
	{
		name: "Pineapple salsa",
		type: "Condiment",
		appearance:
			"Chopped mixture of pineapple, onions, cilantro, and peppers, vibrant colors",
		flavorProfile: "Sweet, tangy, spicy",
	},
	{
		name: "Avocado slices",
		type: "Fruit",
		appearance: "Creamy green slices",
		flavorProfile: "Buttery, mild, rich",
	},
	{
		name: "Tomato bruschetta topping",
		type: "Condiment",
		appearance: "Diced tomatoes with garlic, onion, and basil, vibrant red",
		flavorProfile: "Fresh, tangy, slightly garlicky",
	},
	{
		name: "Fresh basil",
		type: "Herb",
		appearance: "Bright green, broad leaves",
		flavorProfile: "Sweet, peppery, aromatic",
	},
	{
		name: "Fried leeks",
		type: "Vegetable",
		appearance: "Thinly sliced, golden and crispy",
		flavorProfile: "Mild onion flavor, crunchy",
	},
	{
		name: "Garlic aioli",
		type: "Condiment",
		appearance: "Creamy, pale white",
		flavorProfile: "Rich, garlicky, slightly tangy",
	},
	{
		name: "Spicy pepper jack cheese",
		type: "Cheese",
		appearance: "Creamy white with flecks of hot peppers",
		flavorProfile: "Creamy, spicy, with a bold kick",
	},
	{
		name: "Bacon strips",
		type: "Meat",
		appearance: "Long, red and white stripes, crispy",
		flavorProfile: "Salty, smoky, fatty",
	},
	{
		name: "Sunny-side up egg",
		type: "Protein",
		appearance: "Fried egg with a runny, golden yolk and set whites",
		flavorProfile: "Rich, creamy yolk with delicate, slightly firm whites",
	},
	{
		name: "Guacamole",
		type: "Condiment",
		appearance: "Creamy, pale green",
		flavorProfile:
			"Rich, buttery avocado flavor with hints of lime and cilantro",
	},
	{
		name: "Kimchi",
		type: "Condiment",
		appearance: "Chopped, fermented vegetables, bright red",
		flavorProfile: "Spicy, tangy, and umami",
	},
	{
		name: "Black truffles",
		type: "Luxury ingredient",
		appearance: "Small, knobbly, black",
		flavorProfile: "Earthy, musky, intense umami",
	},
	{
		name: "Buffalo mozzarella",
		type: "Cheese",
		appearance: "Soft, white, moist spheres",
		flavorProfile: "Mild, milky, with a delicate texture",
	},
	{
		name: "Smoked brisket",
		type: "Meat",
		appearance: "Thick slices of reddish-pink meat with a smoky outer edge",
		flavorProfile: "Rich, deeply smoky, tender",
	},
	{
		name: "Apple slices",
		type: "Fruit",
		appearance: "Thin, crisp, light green or red",
		flavorProfile: "Sweet, slightly tart, crunchy",
	},
	{
		name: "Dijon mustard",
		type: "Condiment",
		appearance: "Smooth, pale yellow",
		flavorProfile: "Sharp, tangy, with a hint of spice",
	},
	{
		name: "Wasabi mayo",
		type: "Condiment",
		appearance: "Pale green, creamy",
		flavorProfile: "Spicy, pungent, creamy",
	},
	{
		name: "Pulled pork",
		type: "Meat",
		appearance: "Shredded, moist, saucy",
		flavorProfile: "Sweet, smoky, savory",
	},
	{
		name: "Sweet potato fries",
		type: "Topping",
		appearance: "Crispy, golden-orange",
		flavorProfile: "Sweet, starchy, crispy",
	},
	{
		name: "Chorizo slices",
		type: "Meat",
		appearance: "Thin, red, oily",
		flavorProfile: "Spicy, pungent, fatty",
	},
	{
		name: "Ranch dressing",
		type: "Condiment",
		appearance: "Creamy white",
		flavorProfile: "Cool, tangy, herbaceous",
	},
	{
		name: "Crispy fried onions",
		type: "Topping",
		appearance: "Golden, thin, crunchy",
		flavorProfile: "Sweet, crispy, savory",
	},
	{
		name: "Blue corn tortilla chips",
		type: "Topping",
		appearance: "Deep blue, triangular, crispy",
		flavorProfile: "Salty, nutty, crunchy",
	},
	{
		name: "Romaine lettuce",
		type: "Vegetable",
		appearance: "Crisp, green leaves",
		flavorProfile: "Crunchy, watery, mild",
	},
	{
		name: "Roquefort cheese",
		type: "Cheese",
		appearance: "Crumbly, blue veined",
		flavorProfile: "Sharp, tangy, intense blue cheese flavor",
	},
	{
		name: "Fried calamari rings",
		type: "Seafood",
		appearance: "Golden brown, ring-shaped",
		flavorProfile: "Crispy, slightly sweet, briny",
	},
	{
		name: "Maple bacon",
		type: "Meat",
		appearance: "Crispy, glazed with a shiny, sticky surface",
		flavorProfile: "Sweet, smoky, salty",
	},
	{
		name: "Chipotle ketchup",
		type: "Condiment",
		appearance: "Dark red, slightly chunky",
		flavorProfile: "Sweet, smoky, with a mild heat",
	},
	{
		name: "Garlic butter",
		type: "Condiment",
		appearance: "Creamy, pale yellow",
		flavorProfile: "Rich, buttery, strong garlic flavor",
	},
	{
		name: "Jalapeño relish",
		type: "Condiment",
		appearance: "Chopped, bright green with specks of red",
		flavorProfile: "Spicy, tangy, slightly sweet",
	},
	{
		name: "Aged cheddar cheese",
		type: "Cheese",
		appearance: "Firm, pale yellow, slightly crumbly",
		flavorProfile: "Sharp, deep, slightly tangy",
	},
	{
		name: "Mango salsa",
		type: "Condiment",
		appearance: "Chunky, bright orange and red",
		flavorProfile: "Sweet, tangy, slightly spicy",
	},
	{
		name: "Balsamic glaze",
		type: "Condiment",
		appearance: "Dark, thick, sticky",
		flavorProfile: "Sweet, tart, rich",
	},
	{
		name: "Shaved parmesan cheese",
		type: "Cheese",
		appearance: "Thin, light cream flakes",
		flavorProfile: "Sharp, nutty, salty",
	},
	{
		name: "Cajun spice mix",
		type: "Spice",
		appearance: "Fine, reddish-brown powder",
		flavorProfile: "Spicy, smoky, garlicky",
	},
	{
		name: "Sliced avocado",
		type: "Fruit",
		appearance: "Creamy green, smooth slices",
		flavorProfile: "Rich, buttery, mild",
	},
	{
		name: "Pico de gallo",
		type: "Condiment",
		appearance: "Chunky, fresh, colorful with tomatoes, onions, cilantro",
		flavorProfile: "Fresh, tangy, slightly spicy",
	},
	{
		name: "Green chili sauce",
		type: "Condiment",
		appearance: "Bright green, smooth",
		flavorProfile: "Spicy, tangy, slightly sweet",
	},
	{
		name: "Tempura shrimp",
		type: "Seafood",
		appearance: "Crispy, light golden batter",
		flavorProfile: "Crispy, mild, slightly sweet",
	},
	{
		name: "Feta crumbles",
		type: "Cheese",
		appearance: "Small, crumbly, white chunks",
		flavorProfile: "Briny, tangy, crumbly",
	},
	{
		name: "Honey mustard",
		type: "Condiment",
		appearance: "Smooth, golden yellow",
		flavorProfile: "Sweet, tangy, with a mild bite",
	},
	{
		name: "Grilled zucchini slices",
		type: "Vegetable",
		appearance: "Long, thin, charred green",
		flavorProfile: "Soft, slightly smoky, mild",
	},
	{
		name: "Sriracha sauce",
		type: "Condiment",
		appearance: "Bright red, smooth",
		flavorProfile: "Hot, garlicky, slightly sweet",
	},
	{
		name: "Crispy shallots",
		type: "Topping",
		appearance: "Thin, golden brown, crunchy",
		flavorProfile: "Sweet, crispy, rich",
	},
	{
		name: "Smoked salmon",
		type: "Seafood",
		appearance: "Thin, orange-pink slices",
		flavorProfile: "Salty, smoky, rich",
	},
	{
		name: "Greek yogurt sauce",
		type: "Condiment",
		appearance: "Thick, creamy white",
		flavorProfile: "Tangy, cool, smooth",
	},
	{
		name: "Pickled jalapeños",
		type: "Condiment",
		appearance: "Sliced, bright green",
		flavorProfile: "Spicy, tangy, crisp",
	},
	{
		name: "Crispy bacon bits",
		type: "Meat",
		appearance: "Small, crunchy, deep red-brown",
		flavorProfile: "Salty, fatty, intense smoky flavor",
	},
	{
		name: "Sautéed spinach",
		type: "Vegetable",
		appearance: "Wilted, dark green",
		flavorProfile: "Earthy, slightly sweet, tender",
	},
	{
		name: "Pepperoni slices",
		type: "Meat",
		appearance: "Thin, bright red, oily",
		flavorProfile: "Spicy, salty, slightly smoky",
	},
	{
		name: "Goat cheese crumbles",
		type: "Cheese",
		appearance: "Soft, crumbly, white",
		flavorProfile: "Tangy, creamy, distinct",
	},
	{
		name: "Teriyaki glaze",
		type: "Condiment",
		appearance: "Thick, dark brown, glossy",
		flavorProfile: "Sweet, slightly salty, rich umami flavor",
	},
	{
		name: "Sesame oil",
		type: "Oil",
		appearance: "Clear, light yellow",
		flavorProfile: "Nutty, rich, aromatic",
	},
	{
		name: "Fresh mozzarella",
		type: "Cheese",
		appearance: "Soft, white, moist",
		flavorProfile: "Mild, milky, creamy",
	},
	{
		name: "Cucumber slices",
		type: "Vegetable",
		appearance: "Thin, crisp, pale green",
		flavorProfile: "Fresh, watery, mild",
	},
	{
		name: "Anchovy fillets",
		type: "Seafood",
		appearance: "Small, thin, greyish",
		flavorProfile: "Salty, fishy, intense umami",
	},
	{
		name: "Roasted garlic cloves",
		type: "Condiment",
		appearance: "Soft, golden brown",
		flavorProfile: "Sweet, mellow, rich",
	},
	{
		name: "Pesto sauce",
		type: "Condiment",
		appearance: "Green, chunky",
		flavorProfile: "Herbaceous, garlicky, nutty",
	},
	{
		name: "Red cabbage slaw",
		type: "Topping",
		appearance: "Shredded, vibrant purple",
		flavorProfile: "Crunchy, slightly peppery, tangy",
	},
] as const satisfies Ingredient[];
